# Travis build configuration
# https://docs.travis-ci.com/user/customizing-the-build/
language: go
sudo: required

# Version of go to use
go:
  - "1.15.x"

# Placed source code under GOPATH
go_import_path: github.com/skycoin/cx

# Define global variables
env:
  - GOARCH=amd64

# Use a matrix to define SO and possible future changes
matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx

# Install necessaries go packages
install:
  - if [[ ! -d $GOPATH/src/github.com/skycoin/cx ]]; then mkdir -p $GOPATH/src/github.com/skycoin; ln -s $TRAVIS_BUILD_DIR $GOPATH/src/github.com/skycoin/cx; fi
  - cd $GOPATH/src/github.com/skycoin/cx
  - make install
  - make install-gfx-deps
  - make install-linters

# Build, test & run cx test
# Block PR if golden files not up to date
script:
  - make build-full
  - make test
  - make test-full
  - make lint

# Notifications to Telegram channel
notifications:
  email: false
  # https://github.com/kvld/travisci-telegram TravisCI Telegram Bot integration
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
