
[node]
  blockchain_pubkey_str = "02583e5ebbf85522474e0f17e681e62ca37910db6b8792763af4e97663c31a7984"
  blockchain_seckey_str = ""
  create_block_burn_factor = 100
  create_block_max_transaction_size = 134217728
  default_connections = []
  genesis_address_str = "23v7mT1uLpViNKZHh9aww4VChxizqKsNq4E"
  genesis_coin_volume = 10000000000.0
  genesis_signature_str = ""
  genesis_timestamp = 1426562704
  max_block_size = 134217728
  max_block_transactions_size = 134217728
  peer_list_url = "https://127.0.0.1/peers.txt"
  port = 6000
  unconfirmed_burn_factor = 100
  unconfirmed_max_transaction_size = 134217728
  web_interface_port = 6420

[params]
  distribution_addresses = ["TkyD4wD64UE6M5BkNQA17zaf7Xcg4AufwX","2PBcLADETphmqWV7sujRZdh3UcabssgKAEB"]
  distribution_addresses_total = 2
  initial_unlocked_count = 2
  max_coin_supply = 100000000.0
  user_burn_factor = 100
  user_max_transaction_size = 134217728
